name: Update ServiceNow Change Request

on:
  push:
    branches: [ main ]  # Trigger sur push, ou adapte (ex. workflow_dispatch pour manuel)

jobs:
  update-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Change Request
        uses: ServiceNow/servicenow-devops-update-change@v3.1.0
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USERNAME }}  # Username de ton user créé (ex. github-devops-user)
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}  # Password associé
          instance-url: ${{ secrets.SN_INSTANCE_URL }}  # URL de ton instance (ex. https://louisvuittondev.service-now.com)
          context-github: ${{ toJSON(github) }}  # Contexte GitHub auto-généré
          change-request-number: 'CHG0032798'  # Numéro du change à updater (ex. de ton doc)
          change-request-details: '{"short_description":"Mise à jour routine","description":"Maintenance automatisée via CI/CD.","justification":"Routine maintenance 3.0","implementation_plan":"Déploiement testé via pipeline.","backout_plan":"Rollback vers version précédente si échec.","test_plan":"Vérification post-déploiement."}'  # Détails JSON du change

      # Optionnel : Affiche le statut en sortie
      - name: Echo Update Status
        run: echo "Status de l'update: ${{ steps.update-change.outputs.status }}"
